# Generated by Django 4.1.1 on 2022-10-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questmap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="x",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="y",
        ),
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=6)),
                ("y", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="questmap.quest"
                    ),
                ),
            ],
        ),
    ]
